image: python
stages:
  - 'gpu_prep'
  - matrix_2

before_script:
  - python -V              
  - pip install virtualenv 
  - virtualenv venv
  - source venv/bin/activate
  - pip install torch

cache:
  paths:
    - venv/
    - .cache/pip
    
gpu_prep:
  stage: gpu_prep

  script:
    -  apt-get install \
    -  apt-transport-https \
    - ca-certificates \
    - curl \
    - gnupg-agent \
    -   software-properties-common 
    - reboot 
    - gcc --version
    - lshw -C display

    - python GPU_Status.py
    - echo "done"
  artifacts:
    paths:
      - 'outfile.npy'
      
matrix_2:
  stage: matrix_2

  script:

    - echo "done"
  artifacts:
    paths:
      - 'outfile_2.npy'
      
