image: python
stages:
  - 'gpu_test'
  - matrix_2

before_script:
  - python -V              
  - pip install virtualenv 
  - virtualenv venv
  - source venv/bin/activate
  - pip install torch

cache:
  paths:
    - venv/
    - .cache/pip
    
gpu_test:
  stage: gpu_test

  script:
    - python GPU_Status.py
    - echo "done"
  artifacts:
    paths:
      - 'outfile.npy'
      
matrix_2:
  stage: matrix_2

  script:

    - echo "done"
  artifacts:
    paths:
      - 'outfile_2.npy'
      
