image: python
stages:
  - 'gpu_prep'
  - matrix_2

before_script:
  - python -V              
  - pip install virtualenv 
  - virtualenv venv
  - source venv/bin/activate
  - pip install torch

cache:
  paths:
    - venv/
    - .cache/pip
    
gpu_prep:
  stage: gpu_prep

  script:
    - nvidia-smi
    - docker login 
    - docker build --no-cache -t nxdens/gpn-pytorch .
    - docker run --gpus all nxdens/gpn-pytorch:latest /bin/bash ./test.sh # change this 
    - docker push nxdens/gpn-pytorch
    - python GPU_Status.py
    - echo "done"
  artifacts:
    paths:
      - 'outfile.npy'
      
matrix_2:
  stage: matrix_2

  script:

    - echo "done"
  artifacts:
    paths:
      - 'outfile_2.npy'
      
