image: nxdens/gpn-pytorch:latest
stages:
  - 'gpu_prep'
  - machine_learning

before_script:
  - python -V              
  - pip install virtualenv 
  - virtualenv venv
  - source venv/bin/activate
  - pip install torch
  - pip install tensorboard 
  - conda install torchvision
  - conda install pytorch_lightning

cache:
  paths:
    - venv/
    - .cache/pip
    
gpu_prep:
  stage: gpu_prep
  tags:
  - linghai

  script:
    - nvidia-smi
    - python GPU_Status.py
    - echo "done"
  artifacts:
    paths:
      - 'outfile.npy'
      
machine_learning:
  stage: machine_learning

  script:
    - python Funmodel.py
    - echo "done"
  artifacts:
    paths:
      - 'outfile_2.npy'
      
