image: nxdens/gpn-pytorch:latest
stages:
  - 'gpu_prep'
  - matrix_2

before_script:
  - python -V              
  - pip install virtualenv 
  - virtualenv venv
  - source venv/bin/activate
  - pip install torch

cache:
  paths:
    - venv/
    - .cache/pip
    
gpu_prep:
  stage: gpu_prep
  tags:
  - linghai

  script:
    - nvidia-smi
    - python GPU_Status.py
    - echo "done"
  artifacts:
    paths:
      - 'outfile.npy'
      
matrix_2:
  stage: matrix_2

  script:

    - echo "done"
  artifacts:
    paths:
      - 'outfile_2.npy'
      
